# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Hackathon2018' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'NVActivityIndicatorView'

  # Pods for Hackathon2018

  target 'Hackathon2018Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hackathon2018UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
